### ISSUE TITLE
DO NOW

### ISSUE THREAD

**Issue by JBYT27** [darkdarcool/thonk#1]
Now all you have to do is make the same text over and over in all languages :)
> Like JS, HTML, whatever

**Comment by darkdarcool** [comment]
ok

**Comment by JBYT27** [comment]
:D

**Comment by darkdarcool** [comment]
done.

**Comment by darkdarcool** [comment]
for a couple.

**Comment by JBYT27** [comment]
okie :D

**Comment by darkdarcool** [comment]
do you wanna make a newer replapi in a different lang?(different from ray's). I was thinking about it and wanted to do it.

**Comment by JBYT27** [comment]
Hmm, maybe, but I'm not very efficient in other pants

**Comment by darkdarcool** [comment]
wut

**Comment by JBYT27** [comment]
Lmfao, sry, it autocorrected langs to pants

**Comment by darkdarcool** [comment]
lol why?

**Comment by JBYT27** [comment]
Idk xD

**Comment by darkdarcool** [comment]
IdK tHe PaNtS!?

**Comment by iop3** [comment]
i dont have auto-correct activated. :/

**Comment by darkdarcool** [comment]
ok
